version: "3"

services:
  afiapi:
    container_name: afiapi
    build: ./afiapi
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  nginx:
    depends_on:
      - afiapi
    build:
      context: ./nginx
      args:
        TLS_CERT_PATH: ${TLS_CERT_PATH}
        TLS_CERT_FILE: ${TLS_CERT_FILE}
        TLS_KEY_FILE: ${TLS_KEY_FILE}
        NGINX_HOST_NAME: ${NGINX_HOST_NAME}
        NGINX_PORT: ${NGINX_PORT}
        BACKEND_HOSTNAME: ${BACKEND_HOSTNAME}
        BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      # Certbot puts the cert in an archive with a changing name, however the symlink in the ${TLS_CERT_PATH} is constant
      # So we point nginx to the symlink but we also need to mount the real volume that the symlink points to read the actual file.
      - ${TLS_CERT_PATH}:${TLS_CERT_PATH}
      - ${TLS_CERT_ARCHIVE_PATH}:${TLS_CERT_ARCHIVE_PATH}
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    restart: always
networks:
  default:
    external:
      name: ${DOCKER_NET}
