version: "3"

services:
  afiapi:
    container_name: afiapi
    build: ./afiapi
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  nginx:
    depends_on:
      - afiapi
    build:
      context: ./nginx
      args:
        TLS_CERT_FILE: ${TLS_CERT_FILE}
        TLS_KEY_FILE: ${TLS_KEY_FILE}
        NGINX_HOST_NAME: ${NGINX_HOST_NAME}
        NGINX_PORT: ${NGINX_PORT}
        BACKEND_HOSTNAME: ${BACKEND_HOSTNAME}
        BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - ${TLS_CERT_PATH}:/etc/certs
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    restart: always
networks:
  default:
    external:
      name: ${DOCKER_NET}
